### ISSUE TITLE
Only display specified systems

### ISSUE THREAD

**Issue by massivebird** [massivebird/arcstat#4]
Arcstat could totally show the status of select systems! Systems could be specified by label.

For example:

```yaml
# config.yaml
systems:
  myds: # system "label"
    display_name: "DS"
    color: [135,215,255]
    path: "ds"
    games_are_directories: false
  # more systems...
```

If I wanted to run arcstat only for info on my DS games, I could hypothetically run something like this:

```bash
arcstat --systems="myds"
```
